### ISSUE TITLE
Search for `heart` returns unexpected result

### ISSUE THREAD

**Issue by dbrnz** [napakalas/anatomy-lookup#1]
Shouldn't `heart` return `UBERON:0000948`?
```
>>> al.search('heart')
('http://purl.obolibrary.org/obo/UBERON_0007100', 'primary circulatory organ', 1.0)
```

Should the contents of `label` be given a higher weighting than `synonym`'s when building the index?

**Comment by napakalas** [comment]
Yes, *label* should have a higher weight than *synonym*.

**Comment by napakalas** [comment]
I work around the synonym terms, adding each term with the original label and predicate. 
As `heart` in `UBERON_0007100` for an example, its predicate is hasNarrowSynonym, so the term becomes `primary circulatory organ has narrow synonym heart`
The result for this case is quite good, but I will make sure of any other related issues.
Here are the result examples:

```
>>> al.search('heart')
('http://purl.obolibrary.org/obo/UBERON_0000948', 'heart', 1.0)

>>> al.search('chambered heart')
('http://purl.obolibrary.org/obo/UBERON_0000948', 'heart', 0.8507346510887146)

>>> al.search('heart chamber')
('http://purl.obolibrary.org/obo/UBERON_0004151', 'cardiac chamber', 0.9196859002113342)
```

**Comment by dbrnz** [comment]
I'm curious as to why the score from searching for `nasophayrnx` is `0.8313` given that a UBERON term with an exact label match has been found.

Is it because of synonyms skewing the weighting?

Would having two indices improve things? One that is built using just `label`, the other being the existing label and synonym index? And then only look for synonyms if a name doesn't have a string label match??

**Comment by napakalas** [comment]
I think that there is a typo for `nasophayrnx`, the label in the UBERON is `nasopharynx `
```
>>> al.search('nasopharynx')
('http://purl.obolibrary.org/obo/UBERON_0001728', 'nasopharynx', 1.0000001192092896
```

Currently, each term, be it a label or a synonym, has its embedding and is placed in a list. Lookup is done by changing the input term to embedding and comparing it with the embeddings in the list. Automatically the results displayed will prioritize labels over synonyms.

**Comment by dbrnz** [comment]
All good -- I had to look really hard though to spot the typo!
